### Task - 12
- 1. create arrays with all the data types available in numpy
- Numpy has 11 Datatypes and the characters used to represent them are:

- integer - i
- boolean - b
- unsigned integer - u
- float - f
- complex float - c
- timedelta - m
- datatime - M
- object - O
- string - S
- unicode string - U
- fixed chunk of memory for other type (void) - V

In [1]:
## creating array with integer in array:
import numpy as np
a = np.array([1,2,3,4,5,6])
print(a)
print(a.dtype)

[1 2 3 4 5 6]
int32


In [2]:
## creating array with booleean in array:
a = np.array([0,1,2,3,4,5], dtype='bool')
print(a)
print(a.dtype)

[False  True  True  True  True  True]
bool


In [4]:
## creating array with unsigned integers in array:
a = np.array([-3,6,5,-6,7,-8], dtype='uint')
print(a)
print(a.dtype)

[4294967293          6          5 4294967290          7 4294967288]
uint32


In [5]:
## creating array with float in array:
a = np.array([8.4,7.67,5.5,8,4.22])
print(a)
print(a.dtype)

[8.4  7.67 5.5  8.   4.22]
float64


In [6]:
## creating array with complex float in array:
a = np.array([10.5,12+3j,64+8j,45])
print(a)
print(a.dtype)

[10.5+0.j 12. +3.j 64. +8.j 45. +0.j]
complex128


In [7]:
## creating array with timedelta in array:
a=np.timedelta64(2, 'W')
print(a)
print(a.dtype)

2 weeks
timedelta64[W]


In [8]:
## creating array with datatime in array:
a=np.array(['2001-02-15', '1999-08-17', '2019-06-23'], dtype='datetime64')
print(a)
print(a.dtype)

['2001-02-15' '1999-08-17' '2019-06-23']
datetime64[D]


In [10]:
## creating array with object in array:
a = np.array(['aravind',15,24], dtype='O')
print(a)
print(a.dtype)

['aravind' 15 24]
object


In [11]:
## creating array with string in array:
a = np.array(['aravind', 'mothukuri', 'oruganti', 'thatha'])
print(a)
print(a.dtype)

['aravind' 'mothukuri' 'oruganti' 'thatha']
<U9


In [12]:
## creating array with unicode in array:
a = np.array([u'\u0394', u'\265E', u'\265F', u'\u2202r'])
print(a)
print(a.dtype)

['Δ' 'µE' 'µF' '∂r']
<U2


In [13]:
## creating array with void in array:
a=np.array([], dtype='V')
print(a)
print(a.dtype)

[]
|V8
